#!/usr/bin/env bash

export RUST_CHANNEL=stable
export RUST_SRC_PATH="$(nix-build '<nixpkgs>' --no-out-link -A rustChannels.$RUST_CHANNEL.rust-src)"/lib/rustlib/src/rust/src
export LD_LIBRARY_PATH="$(nix-build '<nixpkgs>' --no-out-link -A rustChannels.$RUST_CHANNEL.rustc)"/lib:$LD_LIBRARY_PATH
# texlive.combined.scheme-full \

#export LIBCLANG_PATH="$(nix-build '<nixpkgs>' --no-out-link -A llvmPackages.libclang)/lib"

#     cargo-bloat \

# secp256k1 \
     #librsvg \

exec nix-shell -p \
     llvmPackages.libclang pango gdk_pixbuf \
     asciidoc \
     rustChannels.$RUST_CHANNEL.clippy-preview \
     rustChannels.$RUST_CHANNEL.rust \
     autoconf \
     autogen \
     automake \
     bison \
     cairo \
     cppcheck \
     curl \
     dotnet-sdk \
     elmPackages.elm \
     flex \
     gdb \
     git \
     glfw \
     glib \
     gmp \
     go \
     gtk3 \
     haskellEnv \
     imagemagick \
     libappindicator \
     libgcrypt \
     libgit2 \
     libical.{dev,out} \
     libtool \
     libxml2 \
     mesa_noglu \
     nodejs \
     obs-studio \
     openssl.dev \
     pkg-config \
     pkgconfig \
     protobufc \
     rocksdb \
     rustracer \
     stdenv \
     'python3.withPackages (p: with p; [bitcoinlib Mako cheroot sphinx pytest-forked pytest_xdist pytest ephemeral_port_reserve flask flaky flake8 xlib virtualenv pylightning])' \
     qrencode \
     SDL2 \
     sqlite \
     tor \
     valgrind.dev \
     xorg.libX11.{man,dev} \
     xorg.libXft \
     zlib \
     "$@"
