#!/usr/bin/env bash

rustChannel=stable

export RUST_SRC_PATH="$(nix-build '<nixpkgs>' --no-out-link -A rustChannels.$rustChannel.rust-src)"/lib/rustlib/src/rust/src

export GNUPGHOME=~/.gnupg/trezor

# texlive.combined.scheme-full \


#    rustChannels.$rustChannel.rust \
#    rustracer \

exec nix-shell -k -p \
     asciidoc \
     libgit2 \
     stdenv \
     secp256k1 \
     openssl.dev \
     autoconf \
     autogen \
     automake \
     bison \
     cairo \
     pkgconfig \
     haskellEnv \
     elmPackages.elm \
     libappindicator \
     ncurses \
     llvmPackages.libclang \
     cppcheck \
     dotnet-sdk \
     flex \
     gdb \
     git \
     glfw \
     glib \
     gmp \
     gtk3 \
     imagemagick \
     libical.{dev,out} \
     librsvg \
     libtool \
     libxml2 \
     mesa_noglu \
     nodejs \
     pkgconfig \
     obs-studio \
     'python3.withPackages (p: with p; [bitcoinlib cheroot sphinx pytest-forked pytest_xdist pytest flask flaky flake8 xlib])' \
     qrencode \
     SDL2 \
     sqlite \
     tor \
     valgrind.dev \
     xorg.libX11.{man,dev} \
     xorg.libXft \
     zlib \
     "$@"
