#!/usr/bin/env bash

kill_browser () {
  exec pkill qutebrowser
  #exec pkill --oldest chromium
}

if [ "$1" == "kill" ]; then
  kill_browser
fi

#exec chrome "$@"
exec qutebrowser --enable-webengine-inspector "$@"
