#!/usr/bin/env bash
#exec chrome "$@"

kill_browser () {
  #exec pkill qutebrowser
  exec pkill --oldest chromium
}
chromium "$@"
#qutebrowser --enable-webengine-inspector "$@"
#exec wmctrl -a qutebrowser
exec wmctrl -a chromium
