#!/bin/sh
FIFO=${1:-"/tmp/cmds"}
mkfifo $FIFO &> /dev/null
while :; do bash < $FIFO && \
  (terminal-notifier -message "Command succeeded"; echo "== OK ==") || \
  (terminal-notifier -message "Command failed"; echo "!! ERR !!") done
