#!/usr/bin/env python

import sys

script_tag = ""
script = len(sys.argv) > 1 and sys.argv[1] or None

if script:
  script_tag = '<script src="%s"></script>' % script

hello = """
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Hello World</title>
    </head>
    <body>
        <h1>Hello World</h1>
    %s
    </body>
</html>
""" % script_tag

print hello
