#!/bin/sh
exec nix-shell -p \
  haskellEnv zlib gdb sqlite \
  autoconf git clang libtool gmp sqlite autoconf autogen automake \
  'python3.withPackages (p: with p; [bitcoinlib])' \
  valgrind asciidoc "$@"
