#!/usr/bin/env bash

services="home-email-notifier work-email-notifier email-notify-switcher"

export SYSTEMD_COLORS=1

ctl () {
    printf "%s-ing %s email notifier\n" "$1" "$2" >&2
}

if [ $# -eq 0 ]
then
    printf "nostat [ARGS].. - ARGS: {+,-}{w,h}, +start, -stop\n" >&2
fi

for var in "$@"
do
    case $var in
        +w)
            ctl start work-email-notifier
            touch ~/var/notify/work
            ;;
        -w)
            ctl stop work-email-notifier
            rm -f ~/var/notify/work
            ;;
        +h)
            ctl start home-email-notifier
            touch ~/var/notify/home
            ;;
        -h)
            ctl stop home-email-notifier
            rm -f ~/var/notify/home
            ;;
     esac
done

printf "\n" >&2

ls -1 ~/var/notify
