#!/usr/bin/env sh

notmuch new

# me
notmuch tag +to-me to:jackbox55@gmail.com and not tag:to-me
notmuch tag +to-me to:bill@monstercat.com and not tag:to-me
notmuch tag +to-me to:bill@monster.cat and not tag:to-me
notmuch tag +to-me to:bill@casarin.me and not tag:to-me
notmuch tag +to-me to:bill@casarin.ca and not tag:to-me
notmuch tag +to-me to:will@casarin.ca and not tag:to-me
notmuch tag +to-me to:will@casarin.me and not tag:to-me
notmuch tag +to-me to:william@casarin.ca and not tag:to-me
notmuch tag +to-me to:william@casarin.me and not tag:to-me

notmuch tag +star to:jackbox55+star@gmail.com
notmuch tag +star to:jackbox55+s@gmail.com

notmuch tag +family from:casarin.ca and not tag:to-me
notmuch tag +family from:casarin.me and not tag:to-me
notmuch tag -family tag:to-me

# annoying
notmuch tag -inbox +newsletter from:newsletters.microsoft.com
notmuch tag -inbox +brandalliance from:mail@brandalliancelounge.com
notmuch tag -inbox +newsletter from:freescale
notmuch tag -inbox from:philphys.phil.elte.hu
notmuch tag -inbox from:everything-list.googlegroups.com
notmuch tag -inbox from:codesite-noreply@google.com
notmuch tag -inbox from:getsatisfaction.com
notmuch tag -inbox +deleted from:post@tinyportal.net
notmuch tag -inbox +deleted from:yahoo.com.hk

# work
notmuch tag +alerts +circleci from:builds@circleci.com
notmuch tag +alerts +trello from:trello
notmuch tag +alerts +sentry from:noreply@md.getsentry.com or from:noreply@outbound.getsentry.com
notmuch tag +monstercat to:bill@monstercat.com
notmuch tag +monstercat +connect to:monstercat/connect

# forums
notmuch tag +otr +forums to:otr-users.lists.cypherpunks.ca
notmuch tag +redo +forums to:redo-list.googlegroups.com
notmuch tag +haskell +streaming to:streaming-haskell.googlegroups.com
notmuch tag +component +forums to:componentjs.googlegroups.com
notmuch tag +webvr +forums to:web-vr-discuss.mozilla.org
notmuch tag +crypto +forums to:cryptography.metzdowd.com
notmuch tag +pipes +forums to:haskell-pipes.googlegroups.com
notmuch tag +tcpcrypt +forums to:tcpcrypt.ietf.org
notmuch tag +tcpcrypt +forums to:tcpinc.ietf.org
notmuch tag +haskell +haskell-cafe +forums to:haskell-cafe.haskell.org
notmuch tag +haskell +cabal-dev +forums to:cabal-devel.haskell.org
notmuch tag +haskell +commercial-haskell +forums to:commercialhaskell.googlegroups.com
notmuch tag +haskell +forums to:haskell.haskell.org
notmuch tag +haskell +ghc-devs +forums to:ghc-devs.haskell.org
notmuch tag +haskell +haskell-libraries +forums to:libraries.haskell.org or to:libraries@haskell.org
notmuch tag +cabal2nix +nix +forums to:NixOS/cabal2nix
notmuch tag +nixpkgs +nix +forums to:nixpkgs@noreply.github.com
notmuch tag +nix-dev +nix +forums to:nix-dev@lists.science.uu.nl
