#!/usr/bin/env sh

notmuchcmd () {
  echo "notmuch" "$@"
  $(notmuch "$@")
}

# sent
notmuchcmd tag +sent folder:".Sent"

# k9mail
notmuchcmd tag -inbox folder:".Archive"

# thunderbird I guess?
notmuchcmd tag -inbox folder:".Archives.2017"

# lobsters
notmuchcmd tag +lobsters +busy folder:".Lists.lobsters"

# youtube
notmuchcmd tag +youtube folder:".YouTube"
notmuchcmd tag +talk from:"Talks at Google" and tag:youtube
notmuchcmd tag +lecture from:"Khan Academy" and tag:youtube

# promote noisy lobster stuff to list
notmuchcmd tag -busy +list +haskell tag:lobsters and subject:haskell
notmuchcmd tag -busy +list +icn tag:lobsters and subject:icn
notmuchcmd tag -busy +list +ndn tag:lobsters and subject:ndn
notmuchcmd tag -busy +list +ccnx tag:lobsters and subject:ccnx
notmuchcmd tag -busy +list +nix tag:lobsters and subject:nix
notmuchcmd tag -busy +list +spacemacs tag:lobsters and subject:spacemacs

notmuchcmd tag +arxiv +busy folder:".Arxiv"
notmuchcmd tag +ml tag:arxiv and subject:"stat.ML"

# rss
notmuchcmd tag +rss folder:".RSS"
notmuchcmd tag +rss +reddit +busy folder:".Reddit"
notmuchcmd tag +best +haskell \
     from:"A Neighborhood of Infinity" \
  or from:"Haskell for all" \
  or from:"Lost in Technopolis"

notmuchcmd tag +best +tech from:"Technology Review"
notmuchcmd tag +best +physics +compsci from:from:"Shtetl-Optimized"
notmuchcmd tag +best +haskell +oleg from:"okmij"
notmuchcmd tag +best +edge from:"edge_manager"

notmuchcmd tag +nix \
     from:"Newest questions tagged nix - Stack Overflow" \
  or from:"Thoughts about computer technologies"
notmuchcmd tag +elec +busy from:"Adafruit Industries"
notmuchcmd tag +python from:"Neopythonic"
notmuchcmd tag +physics \
     from:"Physics and cake" \
  or from:"symmetry magazine" \
notmuchcmd tag +ml +best from:"Andrej Karpathy"
notmuchcmd tag +ml from:"Machine Learning"
notmuchcmd tag +haskell \
     from:"Bartosz Milewski" \
  or from:"Haskell" \
  or from:"Declarative Languages Blog"
notmuchcmd tag +gamedev from:"Unity Technologies Blog"
notmuchcmd tag +prog +lisp from:"Peter Norvig"
notmuchcmd tag +startup from:"Paul Graham"
notmuchcmd tag +talk from:"Video Lectures"
notmuchcmd tag +js from:"Vjeux"
notmuchcmd tag +cli +tips from:"UNIX Command Line"
notmuchcmd tag +go from:"Planet 5"
notmuchcmd tag +busy +hack from:"Hackaday"
notmuchcmd tag +vim from:"Vimcasts"
notmuchcmd tag +comic from:"xkcd"
notmuchcmd tag +lesswrong +ai from:"Less Wrong"

# me
notmuchcmd tag +to-me to:jackbox55@gmail.com and not tag:to-me
notmuchcmd tag +to-me to:jb55@jb55.com and not tag:to-me
notmuchcmd tag +to-me to:bill@monstercat.com and not tag:to-me
notmuchcmd tag +to-me to:bill@monster.cat and not tag:to-me
notmuchcmd tag +to-me to:bill@casarin.me and not tag:to-me
notmuchcmd tag +to-me to:bill@casarin.ca and not tag:to-me
notmuchcmd tag +to-me to:will@casarin.ca and not tag:to-me
notmuchcmd tag +to-me to:will@casarin.me and not tag:to-me
notmuchcmd tag +to-me to:william@casarin.ca and not tag:to-me
notmuchcmd tag +to-me to:william@casarin.me and not tag:to-me

notmuchcmd tag +star to:jackbox55+star@gmail.com
notmuchcmd tag +star to:jackbox55+s@gmail.com

notmuchcmd tag +family from:casarin.ca and not tag:to-me
notmuchcmd tag +family from:casarin.me and not tag:to-me
notmuchcmd tag -family tag:to-me

# annoying
notmuchcmd tag -inbox folder:".Updates"
notmuchcmd tag -inbox folder:".Alerts"
notmuchcmd tag -inbox +newsletter from:newsletters.microsoft.com
notmuchcmd tag -inbox +brandalliance from:mail@brandalliancelounge.com
notmuchcmd tag -inbox +newsletter from:freescale
notmuchcmd tag -inbox from:philphys.phil.elte.hu
notmuchcmd tag -inbox from:everything-list.googlegroups.com
notmuchcmd tag -inbox from:codesite-noreply@google.com
notmuchcmd tag -inbox from:getsatisfaction.com
notmuchcmd tag -inbox +deleted from:post@tinyportal.net
notmuchcmd tag -inbox +deleted from:yahoo.com.hk
notmuchcmd tag -inbox +spam folder:".Spam"

# work
notmuchcmd tag +alerts folder:".Alerts"
notmuchcmd tag +alerts +circleci from:builds@circleci.com
notmuchcmd tag +alerts +trello from:trello
notmuchcmd tag +alerts +sentry from:noreply@md.getsentry.com or from:noreply@outbound.getsentry.com
notmuchcmd tag +monstercat to:bill@monstercat.com
notmuchcmd tag +monstercat +connect to:monstercat/connect

# old stuff
notmuchcmd tag +list -forums tag:forums
notmuchcmd tag -nix tag:nixpkgs

# misc
notmuchcmd tag +notmuch subject:notmuch

# forums
notmuchcmd tag +ats +list to:ats-lang-users
notmuchcmd tag +bitcoin +list folder:".Lists.bitcoin"
notmuchcmd tag +cabal2nix +nix +list to:NixOS/cabal2nix
notmuchcmd tag +ccnx +list to:ccnx
notmuchcmd tag +component +list to:componentjs.googlegroups.com
notmuchcmd tag +craigslist +list to:reply.craigslist.org
notmuchcmd tag +crypto +list to:cryptography.metzdowd.com
notmuchcmd tag +elm +list folder:".Lists.elm"
notmuchcmd tag +github +list folder:".GitHub"
notmuchcmd tag +haskell +cabal-dev +list to:cabal-devel.haskell.org
notmuchcmd tag +haskell +commercial-haskell +list to:commercialhaskell.googlegroups.com
notmuchcmd tag +haskell +ghc-devs +list to:ghc-devs.haskell.org
notmuchcmd tag +haskell +haskell-cafe +list to:haskell-cafe.haskell.org
notmuchcmd tag +haskell +haskell-libraries +list to:libraries.haskell.org or to:libraries@haskell.org
notmuchcmd tag +haskell +list to:haskell.haskell.org
notmuchcmd tag +haskell +pipes +list to:haskell-pipes.googlegroups.com
notmuchcmd tag +haskell +streaming to:streaming-haskell.googlegroups.com
notmuchcmd tag +icn +list folder:".Lists.icn"
notmuchcmd tag +ndn +list to:ndn-interest
notmuchcmd tag +nix-dev +nix +list to:nix-dev@lists.science.uu.nl OR to:nix-dev@cs.uu.nl
notmuchcmd tag +nixpkgs +list to:nixpkgs@noreply.github.com
notmuchcmd tag +nixpm +nix +list to:nix@noreply.github.com
notmuchcmd tag +notmuch +list to:notmuch@notmuchmail.org
notmuchcmd tag +otr +list to:otr-users.lists.cypherpunks.ca
notmuchcmd tag +redo +list to:redo-list.googlegroups.com
notmuchcmd tag +shen +list to:qilang
notmuchcmd tag +spacemacs +list to:spacemacs@noreply.github.com
notmuchcmd tag +webvr +vr +list to:web-vr-discuss

# except if someone mentions me
notmuchcmd tag +flagged tag:list and jb55
