#!/usr/bin/env bash

set -e

cd "$HOME/Downloads"

out=$(find . -maxdepth 1 -name '*.pdf' -type f -printf "%T@ %Tc %p\n" \
  | sort -nr \
  | cut -f2- -d" " \
  | dmenu -p docs -l 20 \
  | cut -f3- -d" ")

if [ -z "$out" ]; then
    exit 1
fi

open "$out"
