#!/usr/bin/env bash

#PANDOC='pandoc --metadata=fontfamily:libertine'
PANDOC='pandoc --metadata=fontfamily:libertine -V geometry:margin=1.2in --variable urlcolor=cyan'
#PANDOC='pandoc -V geometry:margin=1.2in --variable urlcolor=cyan'

usage () {
  printf "usage: pdfnow file.md OR <file.md pdfnow [markdown]\n" >&2
  exit 1
}

outfile="$(mktemp)".pdf

if [ -t 0 ]; then
  [ $# -eq 0 ] && usage
  $PANDOC "$1" -o "$outfile"
else
  ext="${1:-markdown}"
  $PANDOC -f "$ext" -o "$outfile"
fi

zathura "$outfile" &>/dev/null

rm "$outfile"
