#!/usr/bin/env bash

usage () {
  printf "usage: pdfnow file.md OR <file.md pdfnow [markdown]\n" >&2
  exit 1
}

outfile=${1:-"$(mktemp)".pdf}

if [ -t 0 ]; then
  [ $# -eq 0 ] && usage
  pdfsave "$1" "$outfile"
else
  outfile="$(mktemp)".pdf
  ext="${1:-markdown}"
  pdfsave "$outfile" "$ext"
fi

zathura "$outfile" &>/dev/null

rm "$outfile"
